sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_4bc2f511cfb7_key -iv $encrypted_4bc2f511cfb7_iv
    -in travis/helseci.key.enc -out travis/helseci.key -d
  - git clone https://github.com/navikt/github-apps-support.git
  - export PATH=`pwd`/github-apps-support/bin:$PATH
  - export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
    $GITHUB_APP_ID`)
  - export COMMIT_SHORT=$(git rev-parse --short HEAD)
  - export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
script:
  - "./gradlew check jar"
  - docker build --pull -t $DOCKER_IMG_NAME:$COMMIT_SHORT .
  - |
    set -e
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      docker push $DOCKER_IMG_NAME:$COMMIT_SHORT
      fi
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
env:
  global:
    - APP_NAME=pleiepengesoknad-prosessering
    - DOCKER_IMG_NAME=navikt/pleiepengesoknad-prosessering
    - GITHUB_APP_ID=19726
    - secure: Y3cqW/iWrbbF9yFhmay0Uh+HOUuB2CXqfLaITosKedbgWkLRZsMzH4FzAMXKsqiHqUoNW+OMB325bhdq6bxWYYBpCm2iJG+Ma0c7u76NiaY2TXmDtul9BJyzmgMQlTs3abF3YiGCkRO1p6nKlbTWMc4/UCj237kYNa4g+KerAy0uAeZ0tSHm7xp6jLDv/lVD/p5CnDtj3g6FpHQCA4mRjXhf0VI2OXM6bzs38DwuDY+6x4gewMO6h+vfVgFoDxpmcoISVQwpoFaU3aIRC1tmZLFI9g6foEWhUN5ymy2FhvTl8LnjevGYDEA8I8kVog5yqrZPXXGZkHMxk7QmGUN0fZYSUDfcJHECuk7uXMSxSJw/AsqzzsaSjLT+2t0xkrP5wI0ydwKqCKRn2cjdV5B4IUKLW5GLl7EAqrOprIPiXDpC/xKJPkdhqtGpcSI3wuyQmqtREyQs1Cp+MS89IqK5nfHSMRSRTEtbaAiZB1WFnPG5SUv95rj5+Kl3M4aNndWKIiz409nMHyZlQer9d3Ix0DTkULfNCIQ0ICiKnUV6++8SpqSPZBVjLALenz5GF/nPYGNrtgdblrPvi1sP+KgS76QiXTEaiRo1MHRNkx6s8YCWqP0I0Fo8Djg9u/UCrbB1AIL6Ymi5i/gtrWCwJAJtm7bvtmv5y9jazgiCQxXAmJM=
    - secure: DYz9PM2MXjUo2qVp5lA1X1J6QWDTKzV1ZjuSCfZHTBDFUer2iED4g97LyTWbK7mhjE3QH7UNecDUDU4aaCPago5BODaZ0+KViJtw3BwaQzsFBnexbfWtqc2ARmoiLiHOjLeQPQ6WYQYJZJ8xkD9zV9Vh8fsV0qCD/wXI0rLuYdBsM+qVuGmA7CgcVf8jGOE8EI9oaO4ikNFvo4PyYzWgzk2xhiw2Rew9Gdk1m/1xZ3gpWkSslfSOsMzD8vxHRyDEj4Uc1YJWKnhiHjt0O9AyeTuho23KhUsLk1C4w90SqS0yjeCRxULdpZSkaXwekrz7JjzNy58dHAU8ChEMpEh0y9ZQSMEIY2PDnHUie6dtHGd2ZxCi02LX2A0Hft69VJe9Eiba9+Tdp/UGMiV+nvok+P+7yGry9K84N5r59QG6apZv2HjD23+2NShz54OHLMbmT71oVONouOZv5teZIi2iepENw7+DrYKbI5o/9KHoK5iA/eHOPBAwbx/98dGDNuDIJdxIUrgdqEV4o34lIie1TvMQc9fVCvzEygOjuJGZVbU0C0+QNejYrlYY6CGlZ3HCaglTzc7xflX6XzbERQkbEQHSvBRphoAjuH88ltVVZLmlSKDQDP8qG+L2JVQeA9pIgGdOPTcK1NBzdg0tIHfrQlwezoRPhuL6IFK0PfcBmNU=