version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

jobs:
  build:
    working_directory: ~/pleiepengesoknad-prosessering
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew check shadowJar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - nais/docker-deploy:
          image: navikt/pleiepengesoknad-prosessering

workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - build:
          context: NAIS deployment
      - nais/deploy:
          name: dev-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepengesoknad-prosessering
          image: navikt/pleiepengesoknad-prosessering
          github-app-id: 35124
          nais-template: nais/dev-fss.yml
          environment: dev-fss
          team: dusseldorf
          filters:
            branches:
              only: master
          requires:
            - build