apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pleiepengesoknad-prosessering
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://pleiepengesoknad-prosessering.nais.preprod.local
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: PLEIEPENGER_OPPGAVE_BASE_URL
      value: https://pleiepenger-oppgave.nais.preprod.local
    - name: PLEIEPENGER_JOARK_BASE_URL
      value: https://pleiepenger-joark.nais.preprod.local
    - name: K9_DOKUMENT_BASE_URL
      value: https://k9-dokument.nais.preprod.local
    - name: AKTOER_REGISTER_BASE_URL
      value: https://app-q1.adeo.no/aktoerregister
    - name: TPS_PROXY_V1_URL
      value: https://tps-proxy-q0.nais.preprod.local/api/v1
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: AZURE_CLIENT_ID
      value: a6aef297-b9c9-4cac-82be-060d4fa68bb8
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: LAGRE_DOKUMENT_SCOPES
      value: 97f0b1bc-6aa9-4d44-a3c7-60b4318fbec4/.default
    - name: SLETTE_DOKUMENT_SCOPES
      value: 97f0b1bc-6aa9-4d44-a3c7-60b4318fbec4/.default
    - name: JOURNALFORE_SCOPES
      value: b32ae17c-0276-4006-9507-4ef49e0e5e20/.default
    - name: OPPRETTE_OPPGAVE_SCOPES
      value: 4bd971d8-2469-434f-9322-8cfe7a7a3379/.default
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443